# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ngmoco-cache-money}
  s.version = "0.2.21"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nick Kallen", "Ashley Martens", "Scott Mace", "John Markos"]
  s.date = %q{2010-10-22}
  s.description = %q{Write-through and Read-through Cacheing for ActiveRecord}
  s.email = %q{teamplatform@ngmoco.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.markdown",
     "TODO"
  ]
  s.files = [
    "README",
     "TODO",
     "UNSUPPORTED_FEATURES",
     "init.rb",
     "lib/cache_money.rb",
     "lib/cash/accessor.rb",
     "lib/cash/buffered.rb",
     "lib/cash/config.rb",
     "lib/cash/fake.rb",
     "lib/cash/finders.rb",
     "lib/cash/index.rb",
     "lib/cash/local.rb",
     "lib/cash/lock.rb",
     "lib/cash/mock.rb",
     "lib/cash/query/abstract.rb",
     "lib/cash/query/calculation.rb",
     "lib/cash/query/primary_key.rb",
     "lib/cash/query/select.rb",
     "lib/cash/request.rb",
     "lib/cash/transactional.rb",
     "lib/cash/util/array.rb",
     "lib/cash/util/marshal.rb",
     "lib/cash/write_through.rb",
     "lib/mem_cached_session_store.rb",
     "lib/mem_cached_support_store.rb",
     "lib/memcached_wrapper.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/ngmoco/cache-money}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Write-through and Read-through Cacheing for ActiveRecord}
  s.test_files = [
    "config/environment.rb",
     "config/memcached.yml",
     "db/schema.rb",
     "spec/cash/accessor_spec.rb",
     "spec/cash/active_record_spec.rb",
     "spec/cash/buffered_spec.rb",
     "spec/cash/calculations_spec.rb",
     "spec/cash/finders_spec.rb",
     "spec/cash/local_buffer_spec.rb",
     "spec/cash/local_spec.rb",
     "spec/cash/lock_spec.rb",
     "spec/cash/marshal_spec.rb",
     "spec/cash/order_spec.rb",
     "spec/cash/transactional_spec.rb",
     "spec/cash/window_spec.rb",
     "spec/cash/write_through_spec.rb",
     "spec/memcached_wrapper_test.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 2.2.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.2.0"])
    else
      s.add_dependency(%q<activerecord>, [">= 2.2.0"])
      s.add_dependency(%q<activesupport>, [">= 2.2.0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 2.2.0"])
    s.add_dependency(%q<activesupport>, [">= 2.2.0"])
  end
end

